Repository OpenVoxProject/vanagon, pull requests merged in 2025-05, with the labels that each got.

#16 specify required ruby versions in different format
  vanagon.gemspec
Labels: skip-changelog

#26 feat: remove eol ruby 2.7 / 3.0 / 3.1 support
  .github/workflows/ruby.yml
  .github/workflows/security.yml
  .rubocop.yml
  lib/git/basic_submodules.rb
  lib/vanagon/component/dsl.rb
  lib/vanagon/component/rules.rb
  lib/vanagon/extensions/set/json.rb
  lib/vanagon/platform.rb
  lib/vanagon/platform/dsl.rb
  lib/vanagon/project.rb
  lib/vanagon/project/dsl.rb
  lib/vanagon/utilities.rb
  spec/lib/vanagon/project_spec.rb
  vanagon.gemspec
Labels: backwards-incompatible

#24 Remove BasicSubmodules and related methods; use native config from git 3.x gem
  lib/git/basic_submodules.rb
  lib/vanagon/component/source/git.rb
  spec/lib/vanagon/component_spec.rb
  vanagon.gemspec
Labels: enhancement
