Repository OpenVoxProject/vanagon, pull requests merged in 2025-08, with the labels that each got.

#48 Add Ubuntu 25.04
  lib/vanagon/platform/defaults/ubuntu-25.04-aarch64.rb
  lib/vanagon/platform/defaults/ubuntu-25.04-amd64.rb
Labels: enhancement

#53 CI: Add proper job we can depend on
  .github/workflows/ruby.yml
Labels: skip-changelog

#51 Respect Provides version in Debian control files
  resources/deb/control.erb
Labels: bug
